version: '3.4'

services:

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
        - "5000:80"
    depends_on:
            - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - airbnb-data:/usr/share/db/data

volumes:
    airbnb-data: